---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mullvad.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts
    version: 3.1.0
    releaseName: qbittorrent
    namespace: qbittorrent
    valuesFile: values.yaml
