---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gluetun-mullvad-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: mullvad
        property: private_key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: mullvad
        property: addresses
