---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"

helmCharts:
  - name: ark-cluster
    repo: https://sickhub.github.io/ark-server-charts
    version: 0.2.2
    releaseName: ark-cluster
    namespace: ark
    valuesFile: values.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: ark-cluster-peeps-tcp
      spec:
        loadBalancerIP: "192.168.8.75"
    target:
      kind: Service
      name: "ark-cluster-peeps-tcp"
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: ark-cluster-peeps-udp
      spec:
        loadBalancerIP: "192.168.8.75"
    target:
      kind: Service
      name: "ark-cluster-peeps-udp"
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ark-cluster-peeps
      spec:
        template:
          spec:
            containers:
            - name: ark-cluster-peeps
              volumeMounts:
                - name: ark-cluster-backup
                  mountPath: /ark/backup
            volumes:
              - name: ark-cluster-backup
                nfs:
                  server: peepums
                  path: /pool01/backup/ark
    target:
      kind: Deployment
      name: "ark-cluster-peeps"
