---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
controllers:
  mealie:
    containers:
      app:
        image:
          repository: ghcr.io/mealie-recipes/mealie
          tag: v1.6.0
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          BASE_URL: "mealie.mcmahan.io"

service:
  web:
    enabled: true
    controller: mealie
    annotations:
      external-dns.alpha.kubernetes.io/hostname: mealie.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 9000

ingress:
  mealie:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: mealie.mcmahan.io
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: web
          port: http
    tls:
    - secretName: 'mealie-cert'
      hosts:
      - mealie.mcmahan.io

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 10Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      mealie:
        app:
          - path: /app/data
