---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apikey.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts
    version: 2.6.0
    releaseName: readarr
    namespace: readarr
    valuesFile: values.yaml
