---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.17
    releaseName: external-secrets
    namespace: external-secrets
    valuesInline:
      metrics:
        service:
          enabled: true
      certController:
        metrics:
          service:
            enabled: true
      webhook:
        metrics:
          service:
            enabled: true

patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: external-secrets-cert-controller-metrics
        labels:
          app.kubernetes.io/metrics: cert-controller
          app.kubernetes.io/name: external-secrets-cert-controller
    target:
      kind: Service
      name: "external-secrets-cert-controller-metrics"
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: external-secrets-webhook
        labels:
          app.kubernetes.io/metrics: webhook
    target:
      kind: Service
      name: "external-secrets-webhook"
