---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - pihole-credentials.yaml

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.14.4
    releaseName: external-dns
    namespace: external-dns
    valuesInline:
      env:
        - name: EXTERNAL_DNS_PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-credentials
              key: password
      registry: noop
      provider: pihole
      extraArgs:
        - --pihole-server=http://pihole-web.pihole.svc
