---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts
    version: 2.6.0
    releaseName: jackett
    namespace: jackett
    valuesFile: values.yaml
