---
controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/jackett
          tag: 0.21.1738
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"

service:
  main:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: jackett.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 9117

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 10Gi
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /config
