---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
controllers:
  homebox:
    containers:
      app:
        image:
          repository: ghcr.io/hay-kot/homebox
          tag: v0.10.3
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          HBOX_OPTIONS_ALLOW_REGISTRATION: "false"

service:
  web:
    enabled: true
    controller: homebox
    annotations:
      external-dns.alpha.kubernetes.io/hostname: homebox.localdomain
    type: LoadBalancer
    ports:
      http:
        port: 80
        targetPort: 7745

ingress:
  homebox:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: homebox.mcmahan.io
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: web
          port: http
    tls:
    - secretName: 'homebox-cert'
      hosts:
      - homebox.mcmahan.io

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 10Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      homebox:
        app:
          - path: /data
