---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-apikey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: default
  target:
    creationPolicy: Owner
  data:
    - secretKey: RADARR__API_KEY
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: radarr
        property: apikey
    - secretKey: APIKEY
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: radarr
        property: apikey
