---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jdmcmahan/home-ops.git
        revision: HEAD
        files:
          - path: "apps/**/kustomization.yaml"
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/jdmcmahan/home-ops.git
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ path.basenameNormalized }}"
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          name: hubble-ca-cert
          jsonPointers:
            - /data/ca.crt
        - group: ""
          kind: Secret
          name: hubble-relay-client-certs
          jsonPointers:
            - /data/ca.crt
            - /data/tls.crt
            - /data/tls.key
        - group: ""
          kind: Secret
          name: hubble-server-certs
          jsonPointers:
            - /data/ca.crt
            - /data/tls.crt
            - /data/tls.key
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: ""
          kind: Service
          jqPathExpressions:
            - .status.loadBalancer.ingress[].ipMode
