---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apikeys.yaml

configMapGenerator:
  - name: recyclarr-configmap
    files:
      - recyclarr.yml=./config/recyclarr.yaml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts
    version: 3.1.0
    releaseName: recyclarr
    namespace: recyclarr
    valuesFile: values.yaml
