---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
controllers:
  recyclarr:
    type: cronjob
    cronjob:
      schedule: "@daily"
      successfulJobsHistory: 1
      failedJobsHistory: 1
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    containers:
      app:
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 6.0.2
          pullPolicy: IfNotPresent
        args:
          - sync
        env:
          COMPlus_EnableDiagnostics: "0"
          TZ: "America/Chicago"
        envFrom:
          - secretRef:
              name: recyclarr-apikeys
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    size: 1Gi
    accessMode: ReadWriteOnce
    advancedMounts:
      recyclarr:
        app:
          - path: /config
  config-file:
    type: configMap
    name: recyclarr-configmap
    globalMounts:
      - path: /config/recyclarr.yml
        subPath: recyclarr.yml
        readOnly: true
