---
kind: Cluster
name: vriska
kubernetes:
  version: v1.30.0
talos:
  version: v1.7.1
features:
  enableWorkloadProxy: true
  backupConfiguration:
    interval: 24h
patches:
  - file: ../patches/cilium-override.yaml
    name: cilium-override
---
kind: ControlPlane
machines:
  - 4c4c4544-004a-4310-8042-b4c04f365132
---
kind: Workers
machines:
  - 4c4c4544-0043-4210-8035-b4c04f365132
  - 4c4c4544-0039-4a10-8048-b9c04f305432
---
kind: Workers
name: storage
machines:
  - 4c4c4544-0052-4610-8054-b3c04f4e5932
  - 4c4c4544-0052-4e10-8054-b3c04f4e5932
  - 4c4c4544-0052-4810-8054-b3c04f4e5932
---
kind: Machine
name: 4c4c4544-004a-4310-8042-b4c04f365132
install:
  disk: /dev/sda
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915-ucode
---
kind: Machine
name: 4c4c4544-0043-4210-8035-b4c04f365132
install:
  disk: /dev/nvme0n1
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915-ucode
---
kind: Machine
name: 4c4c4544-0039-4a10-8048-b9c04f305432
install:
  disk: /dev/nvme0n1
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915-ucode
---
kind: Machine
name: 4c4c4544-0052-4610-8054-b3c04f4e5932
install:
  disk: /dev/nvme0n1
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915-ucode
---
kind: Machine
name: 4c4c4544-0052-4e10-8054-b3c04f4e5932
install:
  disk: /dev/nvme0n1
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915-ucode
---
kind: Machine
name: 4c4c4544-0052-4810-8054-b3c04f4e5932
install:
  disk: /dev/nvme0n1
systemExtensions:
  - siderolabs/intel-ucode
  - siderolabs/i915-ucode
