---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apikeys.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts
    version: 3.1.0
    releaseName: unpackerr
    namespace: unpackerr
    valuesFile: values.yaml
