---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
controllers:
  unpackerr:
    pod:
      securityContext:
        runAsUser: 979
        runAsGroup: 979
        runAsNonRoot: true
        fsGroup: 979
        fsGroupChangePolicy: OnRootMismatch
    containers:
      app:
        image:
          repository: ghcr.io/unpackerr/unpackerr
          tag: 0.13.1
          pullPolicy: IfNotPresent
        env:
          TZ: "America/Chicago"
          UN_WEBSERVER_METRICS: true
          UN_WEBSERVER_LOG_FILE: /logs
          UN_ACTIVITY: true
          UN_SONARR_0_URL: http://sonarr-web.sonarr.svc
          UN_SONARR_0_PATHS_0: /data/staging/torrents/series
          UN_RADARR_0_URL: http://radarr-web.radarr.svc
          UN_RADARR_0_PATHS_0: /data/staging/torrents/movies
          UN_LIDARR_0_URL: http://lidarr-web.lidarr.svc
          UN_LIDARR_0_PATHS_0: /data/staging/torrents/music
          UN_READARR_0_URL: http://readarr-web.readarr.svc
          UN_READARR_0_PATHS_0: /data/staging/torrents/books
        envFrom:
          - secretRef:
              name: unpackerr-apikeys
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

service:
  metrics:
    controller: unpackerr
    ports:
      metrics:
        port: 5656

persistence:
  logs:
    type: emptyDir
  media:
    enabled: true
    type: nfs
    server: peepums
    path: /pool01/media
    advancedMounts:
      unpackerr:
        app:
          - path: /data
