on:
  # push:
  #   branches:    
  #     - main
  #   paths:
  #     - 'infrastructure/sidero/omni/resources/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync cluster templates with Sidero Omni
    steps:
      - name: Checkout cluster templates
        uses: actions/checkout@v4

      - name: Run omnictl
        uses: jdmcmahan/omnictl-action@main
        with:
          working-directory: ./infrastructure/sidero/omni/resources/cluster
          omni-endpoint: ${{ secrets.OMNI_ENDPOINT }}
          omni-service-account-key: ${{ secrets.OMNI_SERVICE_ACCOUNT_KEY }}
          command: omnictl cluster template -f vriska.yaml sync --verbose
